application:
  title: '@project.name@'
  version: '@project.version@'

bookshelf:
  owner: Max Mustermann
  isbn-lookup:
    server: https://example.com/isbn
    api-key: secret

spring:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  sql:
    init:
      mode: always
