application:
  title: '@project.name@'
  version: '@project.version@'

bookshelf:
  owner: Max Mustermann
  isbn-lookup:
    server: https://example.com/isbn
    api-key: secret

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: always

management:
  endpoint:
    health:
      show-details: always
